import type { Property } from "@/types/property";
import type { PropertyCardItem } from "@/types/listings";

export const DUMMY_PROPERTIES: Property[] = [
  {
    id: "1",
    slug: "northfields-house",
    title: "Northfields House",
    listingType: "rent",
    propertyType: "house",
    status: "active",
    address: {
      street: "245 E 90th St APT 4D",
      city: "New York",
      state: "NY",
      zip: "10128",
      country: "US",
      hideAddress: false,
      coordinates: { lat: 40.7794, lng: -73.9496 },
    },
    squareFootage: 1374,
    bedrooms: 3,
    bathrooms: 2,
    monthlyRent: 1999,
    salePrice: null,
    securityDeposit: 1999,
    specialOffer: null,
    showTotalMonthlyPrice: true,
    fees: [],
    dateAvailable: "2026-04-01",
    leaseDuration: "3 Months",
    leaseTerms: "",
    requireRentersInsurance: true,
    media: {
      photos: ["/images/property.jpg"],
      coverPhotoIndex: 0,
      tourUrl: null,
    },
    amenities: {
      laundry: "washer_dryer_included",
      cooling: ["central"],
      heating: ["forced_air"],
      appliances: ["dishwasher", "refrigerator", "microwave"],
      flooring: ["hardwood"],
      parking: ["attached_garage"],
      outdoor: ["balcony_or_deck"],
      accessibility: [],
      other: [],
    },
    screening: {
      petsAllowed: false,
      petPolicyNegotiable: false,
      minIncomeToRentRatio: "3x",
      incomeNegotiable: false,
      minCreditScore: "Good (670-739)",
      creditNegotiable: false,
    },
    contact: {
      listedBy: "owner",
      name: "Kurtesan",
      email: "hey@kurtesan.com",
      phone: null,
      allowPhoneContact: true,
      emailVerified: true,
      emailVerifiedAt: "2026-03-06",
    },
    acceptOnlineApplications: true,
    bookToursInstantly: true,
    description:
      "A beautiful Edwardian family home, barely 6 miles from the Sussex coast, with a grass tennis court and outdoor heated pool.",
    ownerId: "user_1",
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-06T00:00:00Z",
    publishedAt: "2026-03-06T00:00:00Z",
    savedCount: 24,
    viewCount: 312,
    tag: "Bathed in natural light",
    featured: true,
    featuredDescription:
      "A beautiful Edwardian family home, barely 6 miles from the Sussex coast, with a grass tennis court and outdoor heated pool.",
  },
  {
    id: "2",
    slug: "modern-villa-aspen",
    title: "Modern Villa in Aspen",
    listingType: "rent",
    propertyType: "house",
    status: "active",
    address: {
      street: "452 Highland Dr",
      city: "Aspen",
      state: "CO",
      zip: "81611",
      country: "US",
      hideAddress: false,
      coordinates: { lat: 39.1911, lng: -106.8175 },
    },
    squareFootage: 1850,
    bedrooms: 3,
    bathrooms: 2,
    monthlyRent: 5400,
    salePrice: null,
    securityDeposit: 5400,
    specialOffer: null,
    showTotalMonthlyPrice: true,
    fees: [],
    dateAvailable: "2026-04-01",
    leaseDuration: "12 Months",
    leaseTerms: "",
    requireRentersInsurance: false,
    media: {
      photos: ["/images/property.jpg"],
      coverPhotoIndex: 0,
      tourUrl: null,
    },
    amenities: {
      laundry: "washer_dryer_included",
      cooling: ["central"],
      heating: ["heat_pump"],
      appliances: ["dishwasher", "oven", "refrigerator"],
      flooring: ["hardwood", "tile"],
      parking: ["attached_garage"],
      outdoor: ["balcony_or_deck", "pool"],
      accessibility: [],
      other: ["furnished"],
    },
    screening: {
      petsAllowed: true,
      petPolicyNegotiable: true,
      minIncomeToRentRatio: "3x",
      incomeNegotiable: false,
      minCreditScore: null,
      creditNegotiable: false,
    },
    contact: {
      listedBy: "owner",
      name: "Alex Johnson",
      email: "alex@example.com",
      phone: "+1 555 0101",
      allowPhoneContact: true,
      emailVerified: true,
      emailVerifiedAt: "2026-02-15",
    },
    acceptOnlineApplications: true,
    bookToursInstantly: true,
    description: "Stunning modern villa with mountain views, open floor plan, and premium finishes throughout.",
    ownerId: "user_1",
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
    publishedAt: "2026-03-01T00:00:00Z",
    savedCount: 58,
    viewCount: 720,
    tag: "Bathed in natural light",
  },
  {
    id: "3",
    slug: "sunset-boulevard-penthouse",
    title: "Sunset Boulevard Penthouse",
    listingType: "rent",
    propertyType: "condo",
    status: "active",
    address: {
      street: "1022 Sunset Blvd",
      city: "Los Angeles",
      state: "CA",
      zip: "90026",
      country: "US",
      hideAddress: false,
      coordinates: { lat: 34.0774, lng: -118.2594 },
    },
    squareFootage: 2400,
    bedrooms: 4,
    bathrooms: 3,
    monthlyRent: 8200,
    salePrice: null,
    securityDeposit: 8200,
    specialOffer: {
      startDate: "2026-04-01",
      endDate: "2026-06-30",
      description: "Get $500 off your first month when you sign by May 15.",
    },
    showTotalMonthlyPrice: true,
    fees: [
      {
        id: "fee_1",
        category: "utilities",
        name: "Utilities fee",
        paymentFrequency: "monthly",
        format: "fixed",
        amount: 150,
        isRequired: "required",
        isRefundable: false,
        description: "Covers water and trash",
      },
    ],
    dateAvailable: "2026-05-01",
    leaseDuration: "24 Months",
    leaseTerms: "No subletting. Tenant responsible for utilities.",
    requireRentersInsurance: true,
    media: {
      photos: ["/images/property.jpg"],
      coverPhotoIndex: 0,
      tourUrl: "https://my.matterport.com/show/?m=example",
    },
    amenities: {
      laundry: "washer_dryer_included",
      cooling: ["central"],
      heating: ["forced_air"],
      appliances: ["dishwasher", "microwave", "oven", "refrigerator", "freezer"],
      flooring: ["hardwood"],
      parking: ["attached_garage"],
      outdoor: ["balcony_or_deck"],
      accessibility: ["disabled_access"],
      other: ["furnished"],
    },
    screening: {
      petsAllowed: false,
      petPolicyNegotiable: false,
      minIncomeToRentRatio: "3x",
      incomeNegotiable: false,
      minCreditScore: "Very Good (740-799)",
      creditNegotiable: false,
    },
    contact: {
      listedBy: "management",
      name: "Sunset Properties LLC",
      email: "rentals@sunsetprops.com",
      phone: "+1 555 0202",
      allowPhoneContact: true,
      emailVerified: true,
      emailVerifiedAt: "2026-01-10",
    },
    acceptOnlineApplications: true,
    bookToursInstantly: false,
    description: "Luxurious penthouse with panoramic city views, rooftop terrace, and concierge service.",
    ownerId: "user_2",
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
    publishedAt: "2026-03-10T00:00:00Z",
    savedCount: 94,
    viewCount: 1100,
    tag: "Bathed in natural light",
  },
  {
    id: "4",
    slug: "greenway-family-home",
    title: "Greenway Family Home",
    listingType: "rent",
    propertyType: "house",
    status: "rented",
    address: {
      street: "782 Greenway Ln",
      city: "Seattle",
      state: "WA",
      zip: "98101",
      country: "US",
      hideAddress: false,
      coordinates: { lat: 47.6062, lng: -122.3321 },
    },
    squareFootage: 1600,
    bedrooms: 3,
    bathrooms: 2,
    monthlyRent: 3150,
    salePrice: null,
    securityDeposit: 3150,
    specialOffer: null,
    showTotalMonthlyPrice: false,
    fees: [],
    dateAvailable: "2026-07-01",
    leaseDuration: "6 Months",
    leaseTerms: "",
    requireRentersInsurance: false,
    media: {
      photos: ["/images/property.jpg"],
      coverPhotoIndex: 0,
      tourUrl: null,
    },
    amenities: {
      laundry: "shared_or_in_building",
      cooling: ["window"],
      heating: ["baseboard"],
      appliances: ["refrigerator", "oven"],
      flooring: ["carpet", "tile"],
      parking: ["off_street"],
      outdoor: [],
      accessibility: [],
      other: [],
    },
    screening: {
      petsAllowed: true,
      petPolicyNegotiable: false,
      minIncomeToRentRatio: "2.5x",
      incomeNegotiable: true,
      minCreditScore: "Fair (580-669)",
      creditNegotiable: true,
    },
    contact: {
      listedBy: "owner",
      name: "Maria Chen",
      email: "maria@example.com",
      phone: "+1 555 0303",
      allowPhoneContact: false,
      emailVerified: true,
      emailVerifiedAt: "2026-01-20",
    },
    acceptOnlineApplications: true,
    bookToursInstantly: true,
    description: "Cozy family home in quiet neighborhood, close to schools and parks.",
    ownerId: "user_3",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-02-15T00:00:00Z",
    publishedAt: "2026-02-15T00:00:00Z",
    savedCount: 31,
    viewCount: 490,
    tag: "Bathed in natural light",
  },
  {
    id: "5",
    slug: "downtown-family-loft",
    title: "Downtown Family Loft",
    listingType: "sale",
    propertyType: "apartment",
    status: "active",
    address: {
      street: "301 Pine St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
      country: "US",
      hideAddress: false,
      coordinates: { lat: 47.6088, lng: -122.3358 },
    },
    squareFootage: 1200,
    bedrooms: 2,
    bathrooms: 1,
    monthlyRent: null,
    salePrice: 380000,
    securityDeposit: null,
    specialOffer: null,
    showTotalMonthlyPrice: false,
    fees: [],
    dateAvailable: "2026-04-15",
    leaseDuration: "",
    leaseTerms: "",
    requireRentersInsurance: false,
    media: {
      photos: ["/images/property.jpg"],
      coverPhotoIndex: 0,
      tourUrl: null,
    },
    amenities: {
      laundry: "washer_dryer_hookups",
      cooling: ["wall"],
      heating: ["forced_air"],
      appliances: ["dishwasher", "microwave"],
      flooring: ["hardwood"],
      parking: ["off_street"],
      outdoor: [],
      accessibility: [],
      other: [],
    },
    screening: {
      petsAllowed: false,
      petPolicyNegotiable: false,
      minIncomeToRentRatio: null,
      incomeNegotiable: false,
      minCreditScore: null,
      creditNegotiable: false,
    },
    contact: {
      listedBy: "owner",
      name: "James Park",
      email: "james@example.com",
      phone: "+1 555 0404",
      allowPhoneContact: true,
      emailVerified: true,
      emailVerifiedAt: "2026-02-01",
    },
    acceptOnlineApplications: false,
    bookToursInstantly: true,
    description: "Bright urban loft in the heart of downtown Seattle. Walking distance to everything.",
    ownerId: "user_4",
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
    publishedAt: "2026-03-05T00:00:00Z",
    savedCount: 47,
    viewCount: 630,
    tag: "Bathed in natural light",
  },
  {
    id: "6",
    slug: "riverside-condo",
    title: "Riverside Condo",
    listingType: "sale",
    propertyType: "condo",
    status: "active",
    address: {
      street: "55 River Rd",
      city: "Portland",
      state: "OR",
      zip: "97201",
      country: "US",
      hideAddress: false,
      coordinates: { lat: 45.5231, lng: -122.6765 },
    },
    squareFootage: 980,
    bedrooms: 2,
    bathrooms: 2,
    monthlyRent: null,
    salePrice: 290000,
    securityDeposit: null,
    specialOffer: null,
    showTotalMonthlyPrice: false,
    fees: [],
    dateAvailable: "2026-05-01",
    leaseDuration: "",
    leaseTerms: "",
    requireRentersInsurance: false,
    media: {
      photos: ["/images/property.jpg"],
      coverPhotoIndex: 0,
      tourUrl: null,
    },
    amenities: {
      laundry: "shared_or_in_building",
      cooling: ["central"],
      heating: ["heat_pump"],
      appliances: ["dishwasher", "refrigerator"],
      flooring: ["carpet", "hardwood"],
      parking: ["detached_garage"],
      outdoor: ["balcony_or_deck"],
      accessibility: ["disabled_access"],
      other: [],
    },
    screening: {
      petsAllowed: false,
      petPolicyNegotiable: false,
      minIncomeToRentRatio: null,
      incomeNegotiable: false,
      minCreditScore: null,
      creditNegotiable: false,
    },
    contact: {
      listedBy: "management",
      name: "Portland Realty Group",
      email: "info@portlandrealty.com",
      phone: "+1 555 0505",
      allowPhoneContact: true,
      emailVerified: true,
      emailVerifiedAt: "2026-01-05",
    },
    acceptOnlineApplications: false,
    bookToursInstantly: false,
    description: "Modern condo with river views and premium building amenities.",
    ownerId: "user_5",
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-02-28T00:00:00Z",
    publishedAt: "2026-02-28T00:00:00Z",
    savedCount: 19,
    viewCount: 280,
    tag: "Bathed in natural light",
  },
  {
    id: "7",
    slug: "highland-townhouse",
    title: "Highland Townhouse",
    listingType: "rent",
    propertyType: "townhouse",
    status: "active",
    address: {
      street: "88 Oak Ave",
      city: "Denver",
      state: "CO",
      zip: "80203",
      country: "US",
      hideAddress: false,
      coordinates: { lat: 39.7392, lng: -104.9903 },
    },
    squareFootage: 2100,
    bedrooms: 4,
    bathrooms: 3,
    monthlyRent: 4800,
    salePrice: null,
    securityDeposit: 4800,
    specialOffer: null,
    showTotalMonthlyPrice: true,
    fees: [
      {
        id: "fee_2",
        category: "parking",
        name: "Parking fee",
        paymentFrequency: "monthly",
        format: "fixed",
        amount: 100,
        isRequired: "required",
        isRefundable: false,
      },
    ],
    dateAvailable: "2026-04-01",
    leaseDuration: "12 Months",
    leaseTerms: "Tenant responsible for lawn maintenance.",
    requireRentersInsurance: true,
    media: {
      photos: ["/images/property.jpg"],
      coverPhotoIndex: 0,
      tourUrl: null,
    },
    amenities: {
      laundry: "washer_dryer_included",
      cooling: ["central"],
      heating: ["forced_air", "heat_pump"],
      appliances: ["dishwasher", "oven", "refrigerator", "microwave"],
      flooring: ["hardwood", "carpet"],
      parking: ["attached_garage"],
      outdoor: ["balcony_or_deck"],
      accessibility: [],
      other: ["furnished"],
    },
    screening: {
      petsAllowed: true,
      petPolicyNegotiable: false,
      minIncomeToRentRatio: "3x",
      incomeNegotiable: false,
      minCreditScore: "Good (670-739)",
      creditNegotiable: false,
    },
    contact: {
      listedBy: "owner",
      name: "Sarah Williams",
      email: "sarah@example.com",
      phone: "+1 555 0606",
      allowPhoneContact: true,
      emailVerified: true,
      emailVerifiedAt: "2026-02-10",
    },
    acceptOnlineApplications: true,
    bookToursInstantly: true,
    description: "Spacious townhouse in the desirable Highland neighborhood. Great mountain views.",
    ownerId: "user_6",
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-03-08T00:00:00Z",
    publishedAt: "2026-03-08T00:00:00Z",
    savedCount: 52,
    viewCount: 740,
    tag: "Bathed in natural light",
  },
  {
    id: "8",
    slug: "lakeside-retreat",
    title: "Lakeside Retreat",
    listingType: "sale",
    propertyType: "house",
    status: "active",
    address: {
      street: "12 Lakeview Dr",
      city: "Austin",
      state: "TX",
      zip: "73301",
      country: "US",
      hideAddress: false,
      coordinates: { lat: 30.2672, lng: -97.7431 },
    },
    squareFootage: 1750,
    bedrooms: 3,
    bathrooms: 2,
    monthlyRent: null,
    salePrice: 410000,
    securityDeposit: null,
    specialOffer: null,
    showTotalMonthlyPrice: false,
    fees: [],
    dateAvailable: "2026-06-01",
    leaseDuration: "",
    leaseTerms: "",
    requireRentersInsurance: false,
    media: {
      photos: ["/images/property.jpg"],
      coverPhotoIndex: 0,
      tourUrl: null,
    },
    amenities: {
      laundry: "washer_dryer_included",
      cooling: ["central"],
      heating: ["forced_air"],
      appliances: ["dishwasher", "oven", "refrigerator", "microwave", "freezer"],
      flooring: ["hardwood", "tile"],
      parking: ["attached_garage", "off_street"],
      outdoor: ["pool", "balcony_or_deck"],
      accessibility: [],
      other: [],
    },
    screening: {
      petsAllowed: true,
      petPolicyNegotiable: false,
      minIncomeToRentRatio: null,
      incomeNegotiable: false,
      minCreditScore: null,
      creditNegotiable: false,
    },
    contact: {
      listedBy: "owner",
      name: "David Torres",
      email: "david@example.com",
      phone: "+1 555 0707",
      allowPhoneContact: true,
      emailVerified: true,
      emailVerifiedAt: "2026-02-20",
    },
    acceptOnlineApplications: false,
    bookToursInstantly: true,
    description: "Beautiful retreat on the lake with private dock, pool, and mature trees.",
    ownerId: "user_7",
    createdAt: "2026-02-18T00:00:00Z",
    updatedAt: "2026-03-12T00:00:00Z",
    publishedAt: "2026-03-12T00:00:00Z",
    savedCount: 67,
    viewCount: 890,
    tag: "Bathed in natural light",
  },
];

export const DUMMY_PROPERTY_PREVIEWS: PropertyCardItem[] = [
  {
    id: "1",
    listingType: "rent",
    status: "active",
    title: "Northfields House",
    thumbnailUrl: "/images/property.jpg",
    location: { city: "New York", state: "NY", displayAddress: "245 E 90th St APT 4D, New York, NY 10128" },
    pricing: { amount: "1999", currency: "USD", suffix: "/mo" },
    leaseDuration: "3 months",
    basicFacts: { bedrooms: 3, bathrooms: "2.00", squareFootage: 1374 },
    isSaved: false,
    tag: "Bathed in natural light",
    owner: { name: "Kurtesan" },
  },
  {
    id: "2",
    listingType: "rent",
    status: "active",
    title: "Modern Villa in Aspen",
    thumbnailUrl: "/images/property.jpg",
    location: { city: "Aspen", state: "CO", displayAddress: "452 Highland Dr, Aspen, CO 81611" },
    pricing: { amount: "5400", currency: "USD", suffix: "/mo" },
    leaseDuration: "12 months",
    basicFacts: { bedrooms: 3, bathrooms: "2.00", squareFootage: 1850 },
    isSaved: false,
    tag: "Bathed in natural light",
    owner: { name: "Alex Johnson" },
  },
  {
    id: "3",
    listingType: "rent",
    status: "active",
    title: "Sunset Boulevard Penthouse",
    thumbnailUrl: "/images/property.jpg",
    location: { city: "Los Angeles", state: "CA", displayAddress: "1022 Sunset Blvd, Los Angeles, CA 90026" },
    pricing: { amount: "8200", currency: "USD", suffix: "/mo" },
    leaseDuration: "24 months",
    basicFacts: { bedrooms: 4, bathrooms: "3.00", squareFootage: 2400 },
    isSaved: false,
    tag: "Bathed in natural light",
    owner: { name: "Sunset Properties LLC" },
  },
  {
    id: "4",
    listingType: "rent",
    status: "rented",
    title: "Greenway Family Home",
    thumbnailUrl: "/images/property.jpg",
    location: { city: "Seattle", state: "WA", displayAddress: "782 Greenway Ln, Seattle, WA 98101" },
    pricing: { amount: "3150", currency: "USD", suffix: "/mo" },
    leaseDuration: "6 months",
    basicFacts: { bedrooms: 3, bathrooms: "2.00", squareFootage: 1600 },
    isSaved: false,
    tag: "Bathed in natural light",
    owner: { name: "Maria Chen" },
  },
  {
    id: "5",
    listingType: "sale",
    status: "active",
    title: "Downtown Family Loft",
    thumbnailUrl: "/images/property.jpg",
    location: { city: "Seattle", state: "WA", displayAddress: "301 Pine St, Seattle, WA 98101" },
    pricing: { amount: "380000", currency: "USD" },
    leaseDuration: null,
    basicFacts: { bedrooms: 2, bathrooms: "1.00", squareFootage: 1200 },
    isSaved: false,
    tag: "Bathed in natural light",
    owner: { name: "James Park" },
  },
  {
    id: "6",
    listingType: "sale",
    status: "active",
    title: "Riverside Condo",
    thumbnailUrl: "/images/property.jpg",
    location: { city: "Portland", state: "OR", displayAddress: "55 River Rd, Portland, OR 97201" },
    pricing: { amount: "290000", currency: "USD" },
    leaseDuration: null,
    basicFacts: { bedrooms: 2, bathrooms: "2.00", squareFootage: 980 },
    isSaved: false,
    tag: "Bathed in natural light",
    owner: { name: "Portland Realty Group" },
  },
  {
    id: "7",
    listingType: "rent",
    status: "active",
    title: "Highland Townhouse",
    thumbnailUrl: "/images/property.jpg",
    location: { city: "Denver", state: "CO", displayAddress: "88 Oak Ave, Denver, CO 80203" },
    pricing: { amount: "4800", currency: "USD", suffix: "/mo" },
    leaseDuration: "12 months",
    basicFacts: { bedrooms: 4, bathrooms: "3.00", squareFootage: 2100 },
    isSaved: false,
    tag: "Bathed in natural light",
    owner: { name: "Sarah Williams" },
  },
  {
    id: "8",
    listingType: "sale",
    status: "active",
    title: "Lakeside Retreat",
    thumbnailUrl: "/images/property.jpg",
    location: { city: "Austin", state: "TX", displayAddress: "12 Lakeview Dr, Austin, TX 73301" },
    pricing: { amount: "410000", currency: "USD" },
    leaseDuration: null,
    basicFacts: { bedrooms: 3, bathrooms: "2.00", squareFootage: 1750 },
    isSaved: false,
    tag: "Bathed in natural light",
    owner: { name: "David Torres" },
  },
];

export const DUMMY_MY_LISTINGS = [
  {
    id: "2",
    title: "Modern Villa in Aspen",
    address: "452 Highland Dr, Aspen CO",
    status: "active",
    listingType: "rent" as const,
    rent: 5400,
    salePrice: null,
    leaseDuration: "12 Months",
    image: "/images/property.jpg",
  },
  {
    id: "3",
    title: "Sunset Boulevard Penthouse",
    address: "1022 Sunset Blvd, LA CA",
    status: "pending",
    listingType: "rent" as const,
    rent: 8200,
    salePrice: null,
    leaseDuration: "24 Months",
    image: "/images/property.jpg",
  },
  {
    id: "4",
    title: "Greenway Family Home",
    address: "782 Greenway Ln, Seattle WA",
    status: "rented",
    listingType: "rent" as const,
    rent: 3150,
    salePrice: null,
    leaseDuration: "6 Months",
    image: "/images/property.jpg",
  },
  {
    id: "7",
    title: "Highland Townhouse",
    address: "88 Oak Ave, Denver CO",
    status: "active",
    listingType: "rent" as const,
    rent: 4800,
    salePrice: null,
    leaseDuration: "12 Months",
    image: "/images/property.jpg",
  },
  {
    id: "5",
    title: "Downtown Family Loft",
    address: "301 Pine St, Seattle WA",
    status: "active",
    listingType: "sale" as const,
    rent: null,
    salePrice: 380000,
    leaseDuration: "—",
    image: "/images/property.jpg",
  },
  {
    id: "6",
    title: "Riverside Condo",
    address: "55 River Rd, Portland OR",
    status: "active",
    listingType: "sale" as const,
    rent: null,
    salePrice: 290000,
    leaseDuration: "—",
    image: "/images/property.jpg",
  },
  {
    id: "draft-1",
    title: "Lakeside Retreat",
    address: "12 Lakeview Dr, Austin TX",
    status: "drafted",
    listingType: "rent" as const,
    rent: 2800,
    salePrice: null,
    leaseDuration: "12 Months",
    image: "/images/property.jpg",
  },
];
