export const ROUTES = {
  HOME: "/",
  BUY: "/buy",
  GET_MORTGAGE: "/get-a-mortgage",
  FIND_AGENT: "/find-an-agent",
  ADVERTISE: "/advertise",
  RENT: "/rent",
  SELL: "/sell",
  SEARCH: "/search",
  SAVED: "/saved",
  MESSAGES: "/messages",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  PROPERTY: (slug: string) => `/property/${slug}`,
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  OWNER: {
    DASHBOARD: "/dashboard",
    LISTINGS: "/listings",
    CREATE: "/listings/create",
    EDIT: (id: string) => `/listings/${id}/edit`,
    PREVIEW: (id: string) => `/listings/${id}/preview`,
    SALE: "/listings/sale",
    SALE_CREATE: "/listings/sale/create",
    SALE_EDIT: (id: string) => `/listings/sale/${id}/edit`,
    APPLICANTS: "/applicants",
    ANALYTICS: "/analytics",
  },
} as const;
