/** Virtual / 3D tour providers supported for listing tour links (reference parity with major platforms). */
export const SUPPORTED_3D_TOUR_PROVIDERS: readonly string[] = [
  "3DPlans",
  "Asteroom",
  "AtHum",
  "Beyond View",
  "Biganto",
  "Box Brownie",
  "Clay Tours",
  "CloudPano",
  "CubiCasa",
  "Cupix",
  "Epic Drone Tours",
  "EyeSpy360",
  "Get360s",
  "Giraffe360",
  "Go Prop Tech",
  "Google Maps 360",
  "Gryd",
  "Helix Media",
  "iGuide",
  "InsideMaps",
  "Inspection Express",
  "iStaging",
  "IT49",
  "KNTXT",
  "Kuula",
  "Labpano",
  "LCP Media",
  "Listing 3D",
  "Momento360",
  "Momentum Virtual Tours",
  "My Palisade Park",
  "Nodalview",
  "Nucleus 4D",
  "Panoroom",
  "Peek",
  "PlaceVR",
  "PropertyPanorama",
  "Real Vision",
  "RealPage",
  "Repli 3D",
  "Ricoh",
  "Scenic",
  "Sphere",
  "The View",
  "Tour Factory",
  "TourMKR",
  "TrueView360",
  "VPIX",
  "White Branch",
  "Zillow 3D Home",
  "zInspector",
] as const;
